#!/bin/bash

# Update AUR package(s) - Work in Progress

aurUpdate () {
	softName=${1##*/}
	softName=${softName^^}

	gitPull=$(git pull)
	if [[ $gitPull != "Already up to date." ]]; then 
		while : 
		do
			echo
			echo ":: Show git pull output? [Y/n]: "
			read usrGitIn
			usrGitIn=${usrGitIn:0:1} 
			if [[ "${usrGitIn^}" == "Y" ]]; then 
				echo "$gitPull"
				break	
			elif [[ "${usrGitIn^}" == "N" ]]; then
				break
			fi
		done
		
		whileBrk=false
		
		while [[ $whileBrk == false ]];
		do
			echo
			echo ":: Proceed with $softName package build? [Y/n]: "
			read usrIn
			usrIn=${usrIn:0:1}
			if [[ ${usrIn^} == "Y" ]]; then
				makepkg -sri
				while :
				do	
					whileBrk=true
					echo
					echo ":: Clean $softName repo files? [Y/n]: "
					read userChoice
					userChoice=${userChoice:0:1}		
					if [[ ${userChoice^} == "Y" ]]; then
						git clean -fdx
						break
					elif [[ ${userChoice^} == "N" ]]; then
						break
					fi
				done				
				echo
				echo "::: AUR $softName package now updated and installed. :::"
			elif [[ ${firstLet^} == "N" ]]; then
				echo "Alright, maybe next time; Later tater!"
				break
			fi
		done	
	else
		echo
		echo $softName
		echo $gitPull 
    	echo "::: Stay cool :::"
	fi
}

dirLoop () {
	updateDirArr=( $(find ~+ -type f -name "PKGBUILD" 2>&1 | grep -v "Permission denied") )
	
	if [[ $updateDirArr != "" ]]; then	
		for d in ${updateDirArr[@]}
		do
			d=${d%/*}
			cd $d
			if [[ -e .git && -d .git && -e PKGBUILD ]]; then
				aurUpdate $d
			fi
		done
	else
		echo
		echo "Directory does not contain an AUR package."
	fi
}


funcBreak=false

while [[ $funcBreak == false ]]; 
do
	echo
	echo ":: Note: New SSH Hostkeys for AUR Server After Migration: https://www.archlinux.org/news/aur-migration-new-ssh-hostkeys/"
	echo
	echo ":: Run AUR Package Update? Note: you may update a single application by entering the cloned repo folder [Y/n]"
	read resp
	resp=${resp:0:1}
		if [[ ${resp^} == "Y" ]]; then 
			funcBreak=true
			dirLoop
		elif [[ ${resp^} == "N" ]]; then
			echo
			echo "Alrighty."
			exit
		fi
done

