#!/bin/bash

# Update AUR packages in directory
gitPull=$(git pull)
if [[ "$gitPull" != "Already up to date." ]]; then 
	while :
	do
		echo "Show git pull output? (Y/n): "
		read usrGitIn
		firstLetUsrGitIn=${usrGitIn:0:1} 
		if [[ "${firstLetUsrGitIn^}" == "Y" ]]; then 
			echo "$gitPull"
			break
		elif [[ "${firstLetUsrGitIn^}" == "N" ]]; then
			break
		fi
	done
	while :
	do
		echo "Proceed with package build? (Y/n): "
		read usrIn
		firstLet=${usrIn:0:1}
		if [[ "${firstLet^}" == "Y" ]]; then
			makepkg -sri
			while :
			do	
				echo "Clean repo? (Y/n): "
				read userChoice
				firstLetter=${userChoice:0:1}		
				if [[ "${firstLetter^}" == "Y" ]]; then
					git clean -fdx
					break
				elif [[ "${firstLetter^}" == "N" ]]; then
					break
				fi
			done
		elif [[ "${firstLet^}" == "N" ]]; then
			echo "Alright, maybe next time; Later tater!"
			break
		fi
	done	
else
	echo $gitPull 
    echo "Stay classy."
	# exec banner STAY CLASSY 
fi
